### ISSUE TITLE
Py.test reports ERRORS and FAILURES when only FAILURES present

### ISSUE THREAD

**Issue by coagulant** [stj/pytest-django-sqlcount#3]
Happens even when plugin is not activated
Using `pytest==2.8.0`, `django-sqlcounts-0.1.0` version from pypi

```
================================================= ERRORS =================================================
___________________________ ERROR at teardown of TestRateLimit.test_timeslice ____________________________
Traceback (most recent call last):
  File "/Users/prophet/projects/tests/my_tests.py", line 82, in test_timeslice
    self.assertFalse(eta_in_timeslice(eta))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 416, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false
================================================ FAILURES ================================================
______________________________________ TestRateLimit.test_timeslice ______________________________________
Traceback (most recent call last):
  File "/Users/prophet/projects/tests/my_tests.py", line 82, in test_timeslice
    self.assertFalse(eta_in_timeslice(eta))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 416, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false
```

**Comment by stj** [comment]
If you have this issue with django-sqlcount disabled why do you think it is caused by django-sqlcount?

**Comment by coagulant** [comment]
Uninstalling django-sqlcount made errors section go away. I'm using plugins: `django-2.8.0, django-sqlcounts-0.1.0`.

**Comment by coagulant** [comment]
Disabling plugin also restores expected behavior:

```
$ py.test
================================================================== test session starts ==================================================================
platform darwin -- Python 2.7.9, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
plugins: django-2.8.0, django-sqlcounts-0.1.0
======================================================================== ERRORS =========================================================================
____________________________________________________ ERROR at teardown of myAPITest.test_my _____________________________________________________
Traceback (most recent call last):
  File "/Users/prophet/projects/apps/account/tests/my_tests.py", line 14, in test_my
    assert False
AssertionError: assert False
======================================================================= FAILURES ========================================================================
_______________________________________________________________ myAPITest.test_my _______________________________________________________________
Traceback (most recent call last):
  File "/Users/prophet/projects/apps/account/tests/my_tests.py", line 14, in test_my
    assert False
AssertionError: assert False
==================================== 1 failed, 2 passed, 1143 deselected, 2 pytest-warnings, 1 error in 2.54 seconds ====================================


$ py.test -p no:django_sqlcount
================================================================== test session starts ==================================================================
platform darwin -- Python 2.7.9, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
plugins: django-2.8.0
collected 1146 items

apps/account/tests/my_tests.py ..F

======================================================================= FAILURES ========================================================================
_______________________________________________________________ myAPITest.test_my _______________________________________________________________
Traceback (most recent call last):
  File "/Users/prophet/projects/apps/account/tests/my_tests.py", line 14, in test_my
    assert False
AssertionError: assert False
```
